name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run all tests
        run: ./tests/run-tests.sh

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y glib-2.0-dev gettext
      
      - name: Build package
        run: ./package.sh
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.shell-extension.zip
          generate_release_notes: true
          draft: false
          prerelease: false
